// GENERATED by scripts/build-client.mjs — do not edit by hand.
window.__ModuleLoader__.load({
	id: "dsh-scheduled-send",
	factory: (require) => {
		var module = { exports: {} };
		var exports = module.exports;
		Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
		var react = require("react");
		var react_jsx_runtime = react;
// Client-layer core for dsh-scheduled-send (browser side, framework-free and
// testable in Node). The lib/client.js bundle wraps this with React/slots.

const COLLAPSE_THRESHOLD = 3;

/** Client-side note lifetime (fix 3): notes older than this are not rendered. */
const NOTE_TTL_MS = 600_000;

/** Sort a task list by sendAt ascending (display order). */
function sortTasks(tasks) {
  return [...(tasks || [])].sort((a, b) => (a.sendAt || 0) - (b.sendAt || 0));
}

/**
 * Collapse rule for the dock: more than COLLAPSE_THRESHOLD entries render as
 * a single "N 条定时任务 ⌄" summary row the user can expand.
 */
function collapseState(tasks) {
  const list = tasks || [];
  if (list.length <= COLLAPSE_THRESHOLD) {
    return { collapsed: false, visibleCount: list.length, summary: null };
  }
  return { collapsed: true, visibleCount: list.length, summary: `${list.length} 条定时任务 ⌄` };
}

/** Local-timezone "YYYY-MM-DD HH:mm" for a planned send time. */
function formatLocalTime(ms) {
  if (typeof ms !== 'number' || !Number.isFinite(ms)) return '';
  const d = new Date(ms);
  const pad = (n) => String(n).padStart(2, '0');
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}`;
}

/** Countdown until sendAt ("N分N秒后" / "N小时N分后" / "即将发送"). */
function formatCountdown(sendAt, now) {
  const ms = sendAt - now;
  if (ms <= 0) return '即将发送';
  const totalSec = Math.floor(ms / 1000);
  const h = Math.floor(totalSec / 3600);
  const m = Math.floor((totalSec % 3600) / 60);
  const s = totalSec % 60;
  if (h > 0) return `${h}小时${m}分后`;
  if (m > 0) return `${m}分${s}秒后`;
  return `${s}秒后`;
}

/** Default confirmation time = now + 5 minutes. */
function defaultSendAt(now = Date.now(), offsetMs = 5 * 60_000) {
  return now + offsetMs;
}

/**
 * Stateful client controller: polls the host state route, holds the visible
 * task list (optimistically extended right after POST so new entries show
 * WITHOUT a refresh), cooperates in due-time model switches (dir.select then
 * confirm), and exposes cancel.
 * @param {object} deps
 * @param {() => Promise<object>} deps.fetchState GET the host state route
 * @param {(payload:object)=>Promise<{task:object}>} deps.postSchedule
 * @param {(id:string)=>Promise<boolean>} deps.cancelSchedule
 * @param {(taskId:string)=>Promise<boolean>} [deps.confirmModelSwitch]
 * @param {(model:{provider:string,model:string})=>Promise<void>} [deps.selectModel]
 * @param {() => number} [deps.now]
 */
function createScheduledClientState({ fetchState, postSchedule, cancelSchedule, confirmModelSwitch, selectModel, now = () => Date.now() } = {}) {
  let tasks = [];
  let modelSwitchPending = [];
  let delivered = [];
  let timer = null;
  let stopped = false;
  let sessionId = null; // FIX 2: this dock belongs to exactly one conversation
  const handledSwitches = new Set();

  // strict conversation filter (fix 2): with a session bound, only entries
  // belonging to THIS conversation are ever visible; other-session tasks are
  // dropped from the local list on every refresh.
  const own = (it) => !sessionId || !it?.conversationId || it.conversationId === sessionId;

  return {
    /** Bind this client to one conversation (called by both slot injects). */
    setSession(sid) {
      sessionId = sid || null;
      tasks = tasks.filter(own);
    },

    /** Pending tasks sorted ascending by sendAt, own session only. */
    visibleTasks() {
      return sortTasks(tasks).filter(own);
    },
    /** Dismissible model-fallback notes (own session, within NOTE_TTL_MS). */
    lastDelivered() {
      const t = now();
      return delivered.filter(own).filter((n) => n.modelFallback && t - (n.deliveredAt ?? 0) < NOTE_TTL_MS);
    },
    /** Switches the client still owes (own-session filtering at call time). */
    pendingSwitches() {
      return modelSwitchPending.filter(own);
    },
    snapshot() {
      return { tasks: sortTasks(tasks).filter(own), modelSwitchPending: modelSwitchPending.filter(own), recentDelivered: delivered.filter(own), fetchedAt: now() };
    },

    async refresh() {
      const s = await fetchState();
      tasks = (s?.tasks ?? []).filter(own); // strict: stale other-session cache never survives a refresh
      modelSwitchPending = s?.modelSwitchPending ?? [];
      delivered = s?.recentDelivered ?? [];
      return this.snapshot();
    },

    /**
     * User-facing schedule entry: POST to the host route and locally enqueue
     * the returned task so it is visible IMMEDIATELY (无需刷新立即显示).
     * Entries from another conversation are never enqueued locally (fix 2).
     */
    async scheduleMessage(payload) {
      if (!postSchedule) throw new Error('postSchedule 未配置');
      const result = await postSchedule(payload);
      const task = result?.task ?? result;
      if (task?.id && own(task) && !tasks.some((t) => t.id === task.id)) tasks = [...tasks, task];
      return task;
    },

    /** Cancel a pending task: DELETE on the host + drop locally. */
    async cancelTask(id) {
      if (cancelSchedule) await cancelSchedule(id);
      tasks = tasks.filter((t) => t.id !== id);
    },

    /** FIX 3: dismiss one fallback note so it disappears immediately. */
    dismissNote(id) {
      delivered = delivered.filter((n) => n.id !== id);
    },

    /**
     * Due-time model switch cooperation: for each pending switch bound to
     * THIS session, dir.select the model then POST the confirmation. Each
     * taskId is handled at most once per client lifetime.
     */
    async handleModelSwitches(sessionId) {
      if (typeof selectModel !== 'function' || typeof confirmModelSwitch !== 'function') return;
      for (const entry of this.pendingSwitches() || []) {
        if (!entry?.taskId || handledSwitches.has(entry.taskId)) continue;
        if (entry.conversationId && sessionId && entry.conversationId !== sessionId) continue;
        handledSwitches.add(entry.taskId); // mark first: never double-select
        try {
          await selectModel(entry.model);
          await confirmModelSwitch(entry.taskId);
        } catch {
          // switch failed: leave the entry; host times out and degrades to
          // the current model with a surfaced note.
        }
      }
    },

    start(intervalMs = 4_000) {
      if (timer) return;
      stopped = false;
      const loop = async () => {
        if (stopped) return;
        await this.refresh().catch(() => {});
        timer = setTimeout(loop, intervalMs);
        timer.unref?.();
      };
      void loop();
    },

    stop() {
      stopped = true;
      clearTimeout(timer);
      timer = null;
    },
  };
}

// Browser view layer for dsh-scheduled-send.
// This file is CONCATENATED into lib/client.js by scripts/build-client.mjs
// together with src/client-core.js — it must stay import/export-free plain JS.
// Inside the bundle it references: React (platform module) and the client-core
// helpers (sortTasks/collapseState/formatLocalTime/formatCountdown/…).

/* ==== view ==== */
function createClientPluginBody(React) {
  const h = React.createElement;

  function pad2(n) { return String(n).padStart(2, "0"); }

  function toDatetimeLocalValue(ms) {
    const d = new Date(ms);
    return d.getFullYear() + "-" + pad2(d.getMonth() + 1) + "-" + pad2(d.getDate())
      + "T" + pad2(d.getHours()) + ":" + pad2(d.getMinutes());
  }

  /* --- ⏰ composer button (conversation.input.right) -------------------- */
  function ScheduleButton(props) {
    const core = props.core;
    const [open, setOpen] = React.useState(false);
    const [timeValue, setTimeValue] = React.useState("");
    const [modelKey, setModelKey] = React.useState("");
    const [busy, setBusy] = React.useState(false);
    const [error, setError] = React.useState(null);
    // standard session props: useInput(s => s.draft) reads the composer draft
    const draft = typeof props.useInput === "function"
      ? (props.useInput((s) => (s == null ? "" : s.draft)) ?? "")
      : "";

    const openPopover = () => {
      setTimeValue(toDatetimeLocalValue(typeof core.defaultSendAt === "function" ? core.defaultSendAt() : Date.now() + 5 * 60_000));
      setModelKey("");
      setError(null);
      setOpen(true);
    };

    const submit = async () => {
      if (busy) return;
      const content = String(draft ?? "");
      if (!content.trim()) { setError("输入框内容为空，请先输入要定时发送的内容"); return; }
      const at = timeValue ? new Date(timeValue).getTime() : NaN;
      if (!Number.isFinite(at) || at <= Date.now()) { setError("发送时间必须是未来时间"); return; }
      setBusy(true);
      setError(null);
      try {
        const payload = { content, sendAt: at, conversationId: props.sessionId };
        if (modelKey) {
          const i = modelKey.indexOf("::");
          payload.model = { provider: modelKey.slice(0, i), model: modelKey.slice(i + 2) };
        }
        await core.scheduleMessage(payload);
        // spec: 内容转为定时任务并清空输入框 — 绝不立即发送（不调 submit）
        if (props.inputActions && typeof props.inputActions.setDraft === "function") props.inputActions.setDraft("");
        setOpen(false);
      } catch (err) {
        setError(String(err?.message || err));
      } finally {
        setBusy(false);
      }
    };

    const btnStyle = {
      cursor: "pointer", flexShrink: 0, border: "1px solid " + (open ? "#3b82f6" : "transparent"),
      background: open ? "rgba(59,130,246,.12)" : "transparent",
      color: open ? "#3b82f6" : "inherit",
      borderRadius: 999, fontSize: 12, fontWeight: 600, lineHeight: "18px", padding: "1px 8px",
      display: "inline-flex", alignItems: "center", gap: 3,
      opacity: open ? 1 : 0.8,
    };
    const isDark = typeof window !== "undefined" && window.matchMedia && window.matchMedia("(prefers-color-scheme: dark)").matches;
    const popCard = {
      position: "absolute", bottom: "100%", right: 0, marginBottom: 6, zIndex: 30,
      minWidth: 280, padding: "10px 12px", fontSize: 12,
      borderRadius: 12, border: "1px solid " + (isDark ? "rgba(255,255,255,.14)" : "rgba(0,0,0,.10)"),
      background: isDark ? "#1c1c1e" : "#fff",
      boxShadow: "0 8px 24px rgba(0,0,0,.18)",
      color: isDark ? "#eee" : "#111",
    };
    const fieldLbl = { display: "block", fontSize: 11, opacity: .65, margin: "6px 0 3px" };
    const fieldIn = {
      width: "100%", boxSizing: "border-box",
      border: "1px solid " + (isDark ? "rgba(255,255,255,.2)" : "rgba(0,0,0,.18)"),
      borderRadius: 8, padding: "5px 8px", fontSize: 12,
      background: isDark ? "rgba(255,255,255,.05)" : "#fff", color: "inherit",
    };

    return h("div", { "data-plugin": "dsh-scheduled-send-button", style: { position: "relative", display: "inline-flex", alignItems: "center", gap: 6 } }, [
      open
        ? h("span", { key: "badge", style: { flexShrink: 0 } },
            h("span", { style: {
              display: "inline-flex", alignItems: "center", borderRadius: 999,
              padding: "1px 8px", fontSize: 11, fontWeight: 700,
              background: "rgba(59,130,246,.16)", color: "#3b82f6",
            } }, "⏳ 定时发送中"))
        : null,
      h("button", {
        key: "alarm", type: "button", onClick: open ? () => setOpen(false) : openPopover,
        title: "定时发送", "aria-label": "定时发送", style: btnStyle,
      }, "⏰ 定时"),
      open
        ? h("div", { key: "pop", style: popCard }, [
            h("div", { key: "title", style: { fontWeight: 700, fontSize: 13 } }, "定时发送"),
            h("label", { key: "lt", style: fieldLbl }, "发送时间（默认当前 +5 分钟）"),
            h("input", {
              key: "t", type: "datetime-local", value: timeValue,
              onChange: (e) => setTimeValue(e?.target?.value ?? e), style: fieldIn,
            }),
            h("label", { key: "lm", style: fieldLbl }, "到点切换模型（可选）"),
            h("select", {
              key: "m", value: modelKey,
              onChange: (e) => setModelKey(e?.target?.value ?? e), style: fieldIn,
            }, h("option", { key: "none", value: "" }, "不切换模型"),
              ...(props.modelList || []).map((m) =>
                h("option", { key: m.provider + "::" + m.model, value: m.provider + "::" + m.model },
                  (m.name || m.model) + "（" + m.provider + "）"))),
            h("div", { key: "act", style: { display: "flex", gap: 8, marginTop: 10, alignItems: "center" } }, [
              h("button", {
                key: "ok", type: "button", disabled: busy, onClick: submit,
                style: { cursor: busy ? "wait" : "pointer", border: "none", borderRadius: 999, padding: "5px 16px", fontSize: 12, fontWeight: 600, color: "#fff", background: "#3b82f6", opacity: busy ? .6 : 1 },
              }, busy ? "提交中…" : "确认"),
              h("button", {
                key: "no", type: "button", onClick: () => setOpen(false),
                style: { cursor: "pointer", border: "1px solid " + (isDark ? "rgba(255,255,255,.2)" : "rgba(0,0,0,.18)"), borderRadius: 999, padding: "5px 16px", fontSize: 12, background: "transparent", color: "inherit" },
              }, "取消"),
              error ? h("span", { key: "e", style: { color: "#dc2626" } }, error) : null,
            ]),
          ])
        : null,
    ]);
  }

  /* --- pending-task dock (conversation.input.dock) ---------------------- */
  function ScheduledDock(props) {
    const core = props.core;
    const [, setTick] = React.useState(0);
    const [expanded, setExpanded] = React.useState(false);
    React.useEffect(() => {
      let stopped = false;
      let timer = null;
      const loop = async () => {
        if (stopped) return;
        await core.refresh().catch(() => {});
        // cooperate in due-time model switches for THIS session (dir.select +
        // confirm), then re-check shortly after each poll
        await core.handleModelSwitches(props.sessionId);
        if (!stopped) { timer = setTimeout(loop, 3000); timer.unref?.(); }
      };
      void loop();
      const t = setInterval(() => setTick((n) => n + 1), 1000); // countdown ticker
      return () => {
        stopped = true;
        clearTimeout(timer);
        clearInterval(t);
      };
    }, []);

    const tasks = core.visibleTasks();
    const notes = core.lastDelivered();
    if (!tasks.length && !notes.length) return null;
    const st = collapseState(tasks);
    const showEntries = !st.collapsed || expanded;

    const rowStyle = {
      display: "flex", flexDirection: "column", gap: 2, width: "100%", maxWidth: "48rem",
      margin: "2px auto 0", fontSize: 12, lineHeight: "18px",
    };
    const entryStyle = {
      display: "flex", flexDirection: "column", gap: 2, padding: "4px 8px", borderRadius: 8,
      background: "rgba(59,130,246,.10)", border: "1px solid rgba(59,130,246,.22)",
    };
    const srcStyle = {
      margin: 0, whiteSpace: "pre-wrap", fontFamily: "monospace", fontSize: 12,
      wordBreak: "break-word",
    };
    const metaStyle = { display: "flex", alignItems: "center", gap: 8, color: "rgba(128,128,128,1)", flexWrap: "wrap" };
    const cancelBtn = (id) => h("button", {
      key: "x", type: "button", onClick: () => { core.cancelTask(id); },
      style: { cursor: "pointer", border: "1px solid rgba(128,128,128,.4)", borderRadius: 999, padding: "0 8px", fontSize: 11, background: "transparent", color: "inherit" },
    }, "取消");

    return h("div", { "data-plugin": "dsh-scheduled-send-dock", style: rowStyle }, [
      st.collapsed
        ? h("button", {
            key: "sum", type: "button", onClick: () => setExpanded(!expanded),
            style: { cursor: "pointer", alignSelf: "center", border: "1px solid rgba(59,130,246,.35)", borderRadius: 999, padding: "1px 10px", fontSize: 11, fontWeight: 600, background: "rgba(59,130,246,.10)", color: "inherit" },
          }, st.summary)
        : null,
      showEntries
        ? tasks.map((t) => h("div", { key: t.id, style: entryStyle }, [
            h("div", { key: "src", style: srcStyle }, t.content),
            h("div", { key: "meta", style: metaStyle }, [
              h("span", { key: "at" }, formatLocalTime(t.sendAt)),
              h("span", { key: "cd" }, formatCountdown(t.sendAt, Date.now())),
              t.model ? h("span", { key: "m" }, "模型 " + t.model.model) : null,
              h("span", { key: "sp", style: { marginLeft: "auto" } }, cancelBtn(t.id)),
            ]),
          ]))
        : null,
      notes.slice(0, 3).filter((n) => n.modelFallback).map((n) => h("div", {
        key: "note-" + n.id,
        style: { display: "flex", alignItems: "center", gap: 6, padding: "3px 8px", borderRadius: 8, background: "rgba(234,179,8,.14)", color: "inherit", maxWidth: "48rem", margin: "2px auto 0" },
      }, [
        h("span", { key: "txt", style: { flex: 1 } },
          "⚠ 模型切换失败，已按当前模型发送：" + (n.modelError || "未知原因") + "（" + String(n.content ?? "").slice(0, 40) + "）"),
        // fix 3: dismissible — one click and the note is gone for good
        h("button", {
          key: "x", type: "button", "aria-label": "关闭提示",
          onClick: () => { core.dismissNote(n.id); setTick((v) => v + 1); },
          style: { cursor: "pointer", border: "1px solid rgba(128,128,128,.4)", borderRadius: 999, padding: "0 8px", fontSize: 11, background: "transparent", color: "inherit", flexShrink: 0 },
        }, "×"),
      ])),
    ]);
  }

  /** Client plugin body. Returns the cordis plugin ({inject, apply}). */
  return function buildPlugin({ stateRoutePath, fetchImpl }) {
    const schedulePath = stateRoutePath.replace(/\/state$/, "/schedule");
    const modelSelectedPath = stateRoutePath.replace(/\/state$/, "/model-selected");
    const doFetch = fetchImpl || ((...a) => fetch(...a));

    let currentSessionId = null;
    let directoryFor = null; // set in apply() where modelDirectories lives

    const core = createScheduledClientState({
      fetchState: async () => {
        // fix 2: ask the host for THIS conversation's view; the core still
        // filters strictly client-side as a defense against stale caches.
        const q = currentSessionId ? "?conversationId=" + encodeURIComponent(currentSessionId) : "";
        const res = await doFetch(stateRoutePath + q, { headers: { accept: "application/json" } });
        if (!res.ok) throw new Error("state HTTP " + res.status);
        return res.json();
      },
      postSchedule: async (payload) => {
        const res = await doFetch(schedulePath, {
          method: "POST", headers: { "content-type": "application/json", accept: "application/json" },
          body: JSON.stringify(payload),
        });
        const body = await res.json().catch(() => ({}));
        if (!res.ok) throw new Error(body.error || ("HTTP " + res.status));
        return body;
      },
      cancelSchedule: async (id) => {
        const res = await doFetch(schedulePath + "?id=" + encodeURIComponent(id), { method: "DELETE" });
        return res.ok;
      },
      confirmModelSwitch: async (taskId) => {
        const res = await doFetch(modelSelectedPath, {
          method: "POST", headers: { "content-type": "application/json" },
          body: JSON.stringify({ taskId }),
        });
        return res.ok;
      },
      selectModel: async (model) => {
        if (!directoryFor || !currentSessionId) throw new Error("model directory not ready");
        await directoryFor(currentSessionId).select(model); // real client switch entry
      },
    });
    core.defaultSendAt = () => defaultSendAt();

    const inject = ["slots", "modelDirectories"];
    function apply(ctx) {
      ctx.inject(inject, (scope) => {
        directoryFor = (sid) => scope.modelDirectories.directoryFor(sid);
        const modelListFor = (sid) => {
          const snap = scope.modelDirectories.directoryFor(sid)?.store?.getSnapshot?.();
          const out = [];
          for (const g of snap?.groups || []) {
            for (const m of g.models || []) out.push({ provider: g.id, model: m.id, name: m.name || m.id });
          }
          return out;
        };
        scope.slots.inject("conversation.input.right", () => scope.slots.register({
          name: "conversation.input.right",
          id: "dsh-scheduled-send",
          order: 100,
          inject: (sessionId) => {
            currentSessionId = sessionId;
            core.setSession(sessionId); // fix 2: dock/button are conversation-scoped
            return { sessionId, core, modelList: modelListFor(sessionId) };
          },
        }, ScheduleButton));
        scope.slots.inject("conversation.input.dock", () => scope.slots.register({
          name: "conversation.input.dock",
          id: "dsh-scheduled-send",
          order: 30,
          inject: (sessionId) => {
            currentSessionId = sessionId;
            core.setSession(sessionId); // fix 2
            return { sessionId, core };
          },
        }, ScheduledDock));
      });
    }
    return { core, inject, apply };
  };
}

		var built = createClientPluginBody(react)(/* config */ {
			stateRoutePath: "/plugin-data/dsh-scheduled-send/state",
		});
		exports.core = built.core;
		exports.apply = built.apply;
		exports.inject = built.inject;
		return module.exports;
	}
});
